services:
  db:
    image: docker.io/library/postgres:18
    restart: on-failure
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/
    networks:
      - pgnetwork
    
  db_admin:
    image: docker.io/dpage/pgadmin4
    restart: on-failure
    container_name: db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - ./:/var/lib/pgadmin/storage/
    depends_on:
      - db
    networks:
      - pgnetwork

volumes:
  pg-data: {}
networks:
  pgnetwork: {}